config/routes.rb
Rails.application.routes.draw do
  get 'courses/index'

  get 'greeter/hello'
  get 'greeter/goodbye'

  root 'courses#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
#info acquired from coursera API


class Course
	include HTTParty
	base_uri 'https://api.coursera.org/api/catalog.v1/courses'
	default_params fields: "smallIcon,shortDescription", q: "search"
	format :json

	def self.for(term)
		get("", query: {query: term})["elements"]
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
  	@search_query = params[:looking_for] || 'jhu'
  	@courses = Course.for(@search_query)
  end
end

app/controllers/greeter_controller.rb
class GreeterController < ApplicationController
  def hello
  	random_songs = ["'Only Shallow' by My Bloody Valentine", 
			  		"'Good Morning, Captain' by Slint", 
			  		"'Bachelorette' by Björk", 
			  		"'Dance Yrself Clean' by LCD Soundsytem", 
			  		"'Shadowplay' by Joy Division", 
			  		"'How Soon is Now' by the Smiths", 
			  		"'Surgeon' by St. Vincent"]

	@song = random_songs.sample
	@time = Time.now
	#@display_count ||= 0
	#@display_count += 1
  end
  def goodbye
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/greeter_helper.rb
module GreeterHelper
	def time_formatting(time)
		#am/pm times
		time.strftime("%I:%M%p")
	end
end

app/views/courses/index.html.erb
<h1 class = "courselist">Showing classes with search term '<%= @search_query %>'</h1>
<% if @courses.nil? %>
<p> Sorry, no courses found.</p>
<% else %>
<table class = "coursetable">
<tr>
	<th class ="coursehead">Image
	</th>
	<th class ="coursehead">Name
	</th>
	<th class ="coursehead">Description
	</th>
</tr>
	<% @courses.each do |course|%>
	<tr>
	<td class="courseimg"> <%= image_tag(course["smallIcon"])%>
	</td>
	<td class= "coursename"><%= course["name"]%>
	</td>
	<td class = "coursedesc"><%= course["shortDescription"]%>
	</td>
	</tr>
	<% end %>
</table>
	<% end %>

app/views/greeter/goodbye.html.erb
<h1>Thanks for visiting</h1>

app/views/greeter/hello.html.erb
<%  %>

<h1>Greetings</h1>
<p>The song you should be listening to right now is <%= @song %></p>
<p>The time is now <%= @time %></p>

<p>The time is now <%= time_formatting(@time) %></p>

</br>
</br>
</br>
<!--<p> Fun fact: this page has been viewed <%= @display_count %> time(s)</p>-->
<p> <%= link_to "My Github", "https://github.com/sanzstv" %></p></br>
<p> <%= link_to "Leave page", greeter_goodbye_path%></p>

<p> <%= link_to "Learn Python! (because why not?)", courses_index_path%></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Course Search powered by Coursera</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class = "course_search_box">
  <!-- search should be on every page-->
  <%= form_tag(courses_index_path, :method => "get", id: "search-courses") do %>
    <%= text_field_tag :looking_for, params[:looking_for], placeholder: "Search Courses" %>
    <%= submit_tag "Search", :name => nil %>
<% end %>
</div>
    <%= yield %>

  </body>
</html>